### ISSUE TITLE
Write Draft for 010_introduction

### ISSUE THREAD

**Issue by vehrka** [geoinquietosvlc/geovoluntariado-hot-workshop#1]
Write the first draft for the introduction

**Comment by jsanz** [comment]
Taking this task, likely I'll start tomorrow to write something

**Comment by jsanz** [comment]
First batch of content uploaded:
- An small intro on the workshop [frontpage](https://github.com/geoinquietosvlc/geovoluntariado-hot-workshop/blob/develop/source/index.rst)
- OSM motivation, intro to HOT, intro to OSM and OSM Data on the [intro](https://github.com/geoinquietosvlc/geovoluntariado-hot-workshop/blob/develop/source/010_introduccion.rst) page

Contents for editors to be placed.

The read the docs webhook has been configured but not fired so far so, maybe some switches need to be turned on RTD end, no @vehrka ?
