### ISSUE TITLE
Translate OSM Wiki - Mapping Weekend Howto

### ISSUE THREAD

**Issue by vehrka** [geoinquietosvlc/geovoluntariado-hot-workshop#10]
Translate the contents of 

http://wiki.openstreetmap.org/wiki/Mapping_Weekend_Howto

into spanish

Estimate 5h

**Comment by jsanz** [comment]
Translation done and available at 

https://wiki.openstreetmap.org/wiki/ES:Mapping_Weekend_Howto

if @raolbaletco wants to do a second review it would be great :smile:
