### ISSUE TITLE
Write draft for 020_taskmanager

### ISSUE THREAD

**Issue by vehrka** [geoinquietosvlc/geovoluntariado-hot-workshop#2]
Write the draft for the taskmanager

**Comment by shiguera** [comment]
Is this task assigned to me? I don't understand the task

**Comment by jsanz** [comment]
Hi @shiguera 

I've just reviewed your translation, great work!!.

We've placed it on the correct branch and everything is in place so you can take a look on it [here](https://github.com/geoinquietosvlc/learnosm/blob/spanish-coordination/_posts/es/coordination/0500-10-23-tasking-manager.md).

My changes have been mainly of styling, some sentences that weren't translated and a few typos, nothing big.

Again, thank you very much for your help!!
