### ISSUE TITLE
Translate Learnosm Coordination Guide - Reviewing OSM Data

### ISSUE THREAD

**Issue by vehrka** [geoinquietosvlc/geovoluntariado-hot-workshop#7]
The original page
http://learnosm.org/en/coordination/review/

**Comment by jsanz** [comment]
Document [reviewed](https://github.com/geoinquietosvlc/learnosm/commit/d06dfef98379421bca85135ef9739d25d83efbfc?short_path=8c91ddf#diff-8c91ddf976a287b9f3e9eef8712b566b)
