### ISSUE TITLE
Translate LearnOSM Coordination Guide - Tasking Manager

### ISSUE THREAD

**Issue by jsanz** [geoinquietosvlc/geovoluntariado-hot-workshop#9]
The original page:

http://learnosm.org/en/coordination/tasking-manager/

**Comment by jsanz** [comment]
@shiguera te ponemos esta tarea para que nos cuentes qué tal te va con la traducción, si necesitas ayuda o lo que sea.

**Comment by shiguera** [comment]
[Tasking Manager](https://github.com/geoinquietosvlc/learnosm/blob/gh-pages/_posts/es/coordination/0500-10-23-tasking-manager.md) document translated
